default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sinatra-to-rails-pick-1-of-3-challenge_development

test:
  <<: *default
  database: sinatra-to-rails-pick-1-of-3-challenge_test

production:
  <<: *default
  database: sinatra-to-rails-pick-1-of-3-challenge_production
  username: sinatra-to-rails-pick-1-of-3-challenge
  password: <%= ENV['SINATRA-TO-RAILS-PICK-1-OF-3-CHALLENGE_DATABASE_PASSWORD'] %>
